---
language: node_js
node_js:
  - 8.2.1

sudo: false

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install

script:
  - npm run lint
  - npm run prettier-check

notifications:
  email:
    on_success: 'change'
    on_failure: 'change'
